/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.climbsafe.application;

import java.awt.EventQueue;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ComponentUI;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import ca.mcgill.ecse.climbsafe.model.ClimbSafe;
import ca.mcgill.ecse.climbsafe.persistence.ClimbSafePersistence;
import ca.mcgill.ecse.climbsafe.view.ClimbSafePage;

public class ClimbSafeApplication {
  private static ClimbSafe climbSafe;


  public static void main(String[] args) {
	  
	  try {
	      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
	      
	    } catch (UnsupportedLookAndFeelException e) {
	    	
	    } catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InstantiationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    
    EventQueue.invokeLater(ClimbSafePage::new);
  }

  public static ClimbSafe getClimbSafe() {
    ClimbSafePersistence.setFilename("ClimbSafeDemo.data");
    if (climbSafe == null) {
   // these attributes are default, you should set them later with the setters
      climbSafe = ClimbSafePersistence.load();
    }

    return climbSafe;
  }
}
