/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.climbsafe.application;

import java.awt.EventQueue;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import ca.mcgill.ecse.climbsafe.model.ClimbSafe;
import ca.mcgill.ecse.climbsafe.persistence.ClimbSafePersistence;
import ca.mcgill.ecse.climbsafe.view.ClimbSafeMainPage;
import ca.mcgill.ecse.climbsafe.view.ClimbSafePage;

public class ClimbSafeApplication {
	
	
public static final boolean DARK_MODE = true;
private static ClimbSafe climbSafe;

  public String getGreeting() {
    return "Hello World!"; 
  }

  public static void main(String[] args) {
	    // start UI with dark mode, otherwise default mode
	   /* try {
	      UIManager.setLookAndFeel(DARK_MODE ? new FlatDarkLaf() : new FlatLightLaf());
	    } catch (UnsupportedLookAndFeelException e) {
	      // Use regular Swing theme if FlatLaf is unavailable
	    }*/
	    EventQueue.invokeLater(ClimbSafeMainPage::new);
	  }

  public static ClimbSafe getClimbSafe() {
    if (climbSafe == null) {
      // these attributes are default, you should set them later with the setters
      climbSafe = ClimbSafePersistence.load();
    }
    
    return climbSafe;
  }
}
